Switch to setup.cfg (#6)
* Switch to setup.cfg instead of setup.py

* Let's test a Release with the setup.cfg stuff

* [FIX] Classifiers in setup.cfg

* Make docstrings great again!

* Added package discovery to setup.cfg (hopefully)

* setup.py removed

* Makefile updated

* No longer needed command removed

* [FIX] Isolated build

Error: ERROR: pyproject.toml file found.
To use a PEP 517 build-backend you are required to configure tox to use an isolated_build:
https://tox.readthedocs.io/en/latest/example/package.html